name: Daily Perplexity Tasks Automation

# Schedule for Monday-Friday at 19:00 PM (7 PM) UTC
on:
  schedule:
    - cron: '0 19 * * 1-5'  # Monday-Friday at 19:00 UTC
  workflow_dispatch:  # Manual trigger for testing

jobs:
  run-perplexity-automation:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run Perplexity Tasks automation
      env:
        PERPLEXITY_API_KEY: ${{ secrets.PERPLEXITY_API_KEY }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
      run: python perplexity_automation.py
